---
title: "PRB Annual Monitoring Report - interactive dashbaord"
format: html
editor: visual
---

## PRB Annual Monitoring Report

Under [Commission Implementing Regulation (EU) 2019/317](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32019R0317) (herein referred to as the Regulation), monitoring is one of the primary tasks of the [Performance Review Body (PRB)](https://transport.ec.europa.eu/transport-modes/air/single-european-sky/ses-performance-and-charging/performance-review-body_en). It ensures that Member States, the European Commission, and stakeholders are informed about how Air Naviga-tion Service Providers (ANSPs) perform in relation to their performance targets.

The legal basis for monitoring the performance of air traffic management in the SES area is defined in Article 11 of [Regulation (EC) 549/2004](https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX%3A32004R0549) (the Framework Regulation) and in Article 3 of the Regulation.

## SES geographical scope

SES Regulation covers:

-   29 States

-   29 En route charging zones

-   24 Terminal Charging Zones

-   49 ACCs

-   103 Airports

## 2022 Performance - High Level Results

to be added

## Online Monitoring Library

to be added
